- name: Setup secure DNS
  hosts: test
  vars:
    resolvconf_correct: "nameserver 127.0.0.1"

  tasks:
  - name: (Arch) Install stubby and dnsmasq
    community.general.packaging.os.pacman:
      name:
      - stubby
      - dnsmasq
      state: present
    when: ansible_distribution == "Archlinux"

  - name: (Debian) Install stubby and dnsmasq
    ansible.builtin.apt:
      name:
      - stubby
      - dnsmasq
      state: present
    when: ansible_facts.os_family == "Debian"

  - name: (Void) Install stubby and dnsmasq
    community.general.packaging.os.xbps:
      name:
      - stubby
      - dnsmasq
      state: present
    when: ansible_facts.os_family == "void"

  - name: stubby - Remove default upstreams
    ansible.builtin.replace:
      path: /etc/stubby/stubby.yml
      after: "DEFAULT UPSTREAMS"
      before: "OPTIONAL UPSTREAMS"
      regexp: "^(?!=#)(  .*)$"
      replace: "#\\1"

  - name: stubby - uncomment cloudflare (ipv4)
    ansible.builtin.replace:
      dest: /etc/stubby/stubby.yml
      after: "## Cloudflare"
      before: "## The Uncensored DNS servers"
      regexp: "^#(  .*)"
      replace: "\\1"

  - name: stubby - uncomment cloudflare (ipv4)
    ansible.builtin.replace:
      dest: /etc/stubby/stubby.yml
      after: "## Cloudflare servers"
      before: "## Google"
      regexp: "^#(  .*)"
      replace: "\\1"

  - name: stubby - Change listen port to 53000
    ansible.builtin.replace:
      dest: /etc/stubby/stubby.yml
      after: "listen_addresses:"
      regexp: "(- (127.0.0.1|0::1))$"
      replace: "\\1@53000"

  - name: Change dnsmasq connect port to 53000
    ansible.builtin.blockinfile:
      path: /etc/dnsmasq.conf
      insertafter: EOF
      content: |
        no-resolv
        proxy-dnssec
        server=::1#53000
        server=127.0.0.1#53000
        listen-address=::1,127.0.0.1

  - name: dnsmasq - Start and enable service
    ansible.builtin.service:
      name: dnsmasq
      enabled: true
      state: started

  - name: stubby - Start and enable service
    ansible.builtin.service:
      name: stubby
      enabled: true
      state: started

  - name: Read contents of resolv.conf
    ansible.builtin.command: cat /etc/resolv.conf
    changed_when: false
    register: resolvconf_content

  - name: Allow modification of resolv.conf
    ansible.builtin.file:
      path: /etc/resolv.conf
      attr: -i
    when: resolvconf_content.stdout != resolvconf_correct

  - name: Set resolv to localhost (dnsmasq)
    ansible.builtin.copy:
      dest: /etc/resolv.conf
      mode: '0644'
      content: "{{ resolvconf_correct }}\n"
    when: resolvconf_content.stdout != resolvconf_correct

  - name: Prevent modification of resolv.conf
    ansible.builtin.file:
      path: /etc/resolv.conf
      attr: +i
    when: resolvconf_content.stdout != resolvconf_correct
