#+TITLE: Ansible based system setup (ArchLinux)

* Playbook naming convention
| prefix      | purpose                   |
|-------------+---------------------------|
| 0000 - 0099 | base system setup         |
| 0100 - 0199 | non-critical system setup |

* Current playbooks
** =[0100]= DNS over TLS
Based on ArchWiki article: https://wiki.archlinux.org/index.php/Stubby \\
/Stubby/ based proxy with /dnsmasq/ as cache for system-wide forwarding of
DNS queries and responses over secure connections. =/etc/resolv.conf=
is locked with =chattr= to prevent modification. Uses Cloudflare DNS
servers.
#+BEGIN_SRC
-> /etc/resolv.conf
-> localhost:53 (dnsmasq) (might return cached response)
-> localhost:53000 (stubby)
-> 1.1.1.1:53 over TLS (cloudflare)
#+END_SRC
** =[0101]= Alternative docker root dir
- My /var is fairly small (separate partition)
- My docker data dir gets huge (I build many huge images)
- My /home is also separate and is the biggest partition
So I moved /docker data dir/ from =/var/lib/docker= to =/home/docker=.
The playbook copies old data to new location only if new location
doesn't exist, so the process is safe.  Note that despite the location
(which is configurable with a variable) it has nothing to do with
posix system users.
